export const CREATE_PROJECT = "CREATE_PROJECT";
export const CREATE_PROJECT_START = "CREATE_PROJECT_START";
export const CREATE_PROJECT_SUCCESS = "CREATE_PROJECT_SUCCESS";
export const CREATE_PROJECT_FAIL = "CREATE_PROJECT_FAIL";

export const GET_PROJECTS = "GET_PROJECTS";
export const GET_PROJECTS_START = "GET_PROJECTS_START";
export const GET_PROJECTS_SUCCESS = "GET_PROJECTS_SUCCESS";
export const GET_PROJECTS_FAIL = "GET_PROJECTS_FAIL";

export const GET_SINGLE_PROJECT = "GET_SINGLE_PROJECT";
export const GET_SINGLE_PROJECT_START = "GET_SINGLE_PROJECT_START";
export const GET_SINGLE_PROJECT_SUCCESS = "GET_SINGLE_PROJECT_SUCCESS";
export const GET_SINGLE_PROJECT_FAIL = "GET_SINGLE_PROJECT_FAIL";

export const DELETE_PROJECT = "DELETE_PROJECT";
export const DELETE_PROJECT_START = "DELETE_PROJECT_START";
export const DELETE_PROJECT_SUCCESS = "DELETE_PROJECT_SUCCESS";
export const DELETE_PROJECT_FAIL = "DELETE_PROJECT_FAIL";

export const GET_BACKLOG = "GET_BACKLOG";
export const GET_BACKLOG_START = "GET_BACKLOG_START";
export const GET_BACKLOG_SUCCESS = "GET_BACKLOG_SUCCESS";
export const GET_BACKLOG_FAIL = "GET_BACKLOG_FAIL";

export const GET_PROJECT_TASK = "GET_PROJECT_TASK";
export const GET_PROJECT_TASK_START = "GET_PROJECT_TASK_START";
export const GET_PROJECT_TASK_SUCCESS = "GET_PROJECT_TASK_SUCCESS";
export const GET_PROJECT_TASK_FAIL = "GET_PROJECT_TASK_FAIL";

export const DELETE_PROJECT_TASK = "DELETE_PROJECT_TASK";
export const DELETE_PROJECT_TASK_START = "DELETE_PROJECT_TASK_START";
export const DELETE_PROJECT_TASK_SUCCESS = "DELETE_PROJECT_TASK_SUCCESS";
export const DELETE_PROJECT_TASK_FAIL = "DELETE_PROJECT_TASK_FAIL";

export const ADD_PROJECT_TASK = "ADD_PROJECT_TASK";
export const ADD_PROJECT_TASK_START = "ADD_PROJECT_TASK_START";
export const ADD_PROJECT_TASK_SUCCESS = "ADD_PROJECT_TASK_SUCCESS";
export const ADD_PROJECT_TASK_FAIL = "ADD_PROJECT_TASK_FAIL";

export const UPDATE_PROJECT_TASK = "UPDATE_PROJECT_TASK";
export const UPDATE_PROJECT_TASK_START = "UPDATE_PROJECT_TASK_START";
export const UPDATE_PROJECT_TASK_SUCCESS = "UPDATE_PROJECT_TASK_SUCCESS";
export const UPDATE_PROJECT_TASK_FAIL = "UPDATE_PROJECT_TASK_FAIL";

export const CREATE_USER = "CREATE_USER";
export const CREATE_USER_START = "CREATE_USER_START";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const CREATE_USER_FAIL = "CREATE_USER_FAIL";

export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_START = "LOGIN_USER_START";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAIL = "LOGIN_USER_FAIL";

export const LOGOUT_USER = "LOGOUT_USER";
export const LOGOUT_USER_START = "LOGOUT_USER_START";
export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS";
export const LOGOUT_USER_FAIL = "LOGOUT_USER_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const CHECK_AUTHENTICATE = "CHECK_AUTHENTICATE";
